pyinstaller main.py^
 --name serverthrall^
 --workpath .\installer\build^
 --distpath .\installer\dist^
 --specpath .\installer^
 --icon .\installer\icon.ico^
 --console^
 --onedir^
 --onefile^
 --noconfirm^
 --clean^